[metadata]
name = "azik-us"
description = "AZIK typing rule for us keyboard"

# AZIK総合解説書に基づく。独自のものは独自と記載 http://hp.vector.co.jp/authors/VA002116/azik/azikinfo.htm#itiran
# Up, ch, at, mu, AE, ae, OE, oe, ht, ff, cr, lf, nl, vt, IO は各特殊キーにマップされるのでスペースを開ける必要があることに注意

[conversion]

semicolon = ["", "っ"]
bracketright = ["", "」"]
minus = ["", "ー"]

a = ["", "あ"]

"b period" = ["", "ぶ"]
ba = ["", "ば"]
bd = ["", "べん"]
be = ["", "べ"]
bh = ["", "ぶう"]
bi = ["", "び"]
bj = ["", "ぶん"]
bk = ["", "びん"]
bl = ["", "ぼん"]
bn = ["", "ばん"]
bo = ["", "ぼ"]
bp = ["", "ぼう"]
bq = ["", "ばい"]
br = ["", "ばら"]
bt = ["", "びと"]
bu = ["", "ぶ"]
bw = ["", "べい"]
bx = ["", "べい"]
bya = ["", "びゃ"]
byd = ["", "びぇん"]
bye = ["", "びぇ"]
byh = ["", "びゅう"]
byj = ["", "びゅん"]
byl = ["", "びょん"]
byn = ["", "びゃん"]
byo = ["", "びょ"]
byp = ["", "びょう"]
byq = ["", "びゃい"]
byu = ["", "びゅ"]
byw = ["", "びぇい"]
byz = ["", "びゃん"]
bz = ["", "ばん"]

ca = ["", "ちゃ"]
cd = ["", "ちぇん"]
ce = ["", "ちぇ"]
cf = ["", "ちぇ"]
"c h" = ["", "ちゅう"]
ci = ["", "ち"]
cj = ["", "ちゅん"]
ck = ["", "ちん"]
cl = ["", "ちょん"]
cn = ["", "ちゃん"]
co = ["", "ちょ"]
cp = ["", "ちょう"]
cq = ["", "ちゃい"]
cu = ["", "ちゅ"]
cv = ["", "ちゃい"]
cw = ["", "ちぇい"]
cx = ["", "ちぇい"]
cz = ["", "ちゃん"]

da = ["", "だ"]
# 独自
dch = ["", "でゅう"]
dci = ["", "でぃ"]
# 独自。dciの派生
dck = ["", "でぃん"]
dcu = ["", "どぅ"]
dd = ["", "でん"]
de = ["", "で"]
dh = ["", "づう"]
di = ["", "ぢ"]
dj = ["", "づん"]
dk = ["", "ぢん"]
dl = ["", "どん"]
dm = ["", "でも"]
dn = ["", "だん"]
do = ["", "ど"]
dp = ["", "どう"]
dq = ["", "だい"]
ds = ["", "です"]
dt = ["", "だち"]
du = ["", "づ"]
dw = ["", "でい"]
dz = ["", "だん"]

e = ["", "え"]

fa = ["", "ふぁ"]
fd = ["", "ふぇん"]
fe = ["", "ふぇ"]
fh = ["", "ふう"]
fi = ["", "ふぃ"]
fj = ["", "ふん"]
fk = ["", "ふぃん"]
fl = ["", "ふぉん"]
fn = ["", "ふぁん"]
fo = ["", "ふぉ"]
fp = ["", "ふぉー"]
fq = ["", "ふぁい"]
fu = ["", "ふ"]
fw = ["", "ふぇい"]
fz = ["", "ふぁん"]

ga = ["", "が"]
gd = ["", "げん"]
ge = ["", "げ"]
gh = ["", "ぐう"]
gi = ["", "ぎ"]
gj = ["", "ぐん"]
gk = ["", "ぎん"]
gl = ["", "ごん"]
gn = ["", "がん"]
go = ["", "ご"]
gp = ["", "ごう"]
gq = ["", "がい"]
gr = ["", "がら"]
gt = ["", "ごと"]
gu = ["", "ぐ"]
gw = ["", "げい"]
gya = ["", "ぎゃ"]
gyd = ["", "ぎぇん"]
gye = ["", "ぎぇ"]
gyh = ["", "ぎゅう"]
gyj = ["", "ぎゅん"]
gyl = ["", "ぎょん"]
gyn = ["", "ぎゃん"]
gyo = ["", "ぎょ"]
gyp = ["", "ぎょう"]
gyq = ["", "ぎゃい"]
gyu = ["", "ぎゅ"]
gyw = ["", "ぎぇい"]
gyz = ["", "ぎゃん"]
gz = ["", "がん"]

ha = ["", "は"]
hd = ["", "へん"]
he = ["", "へ"]
hga = ["", "ひゃ"]
hgd = ["", "ひぇん"]
hge = ["", "ひぇ"]
hgh = ["", "ひゅう"]
hgj = ["", "ひゅん"]
hgl = ["", "ひょん"]
hgn = ["", "ひゃん"]
hgo = ["", "ひょ"]
hgp = ["", "ひょう"]
hgq = ["", "ひゃい"]
hgu = ["", "ひゅ"]
hgw = ["", "ひぇい"]
hgz = ["", "ひゃん"]
hh = ["", "ふう"]
hi = ["", "ひ"]
hj = ["", "ふん"]
hk = ["", "ひん"]
hl = ["", "ほん"]
hn = ["", "はん"]
ho = ["", "ほ"]
hp = ["", "ほう"]
hq = ["", "はい"]
"h t" = ["", "ひと"]
hu = ["", "ふ"]
hw = ["", "へい"]
hya = ["", "ひゃ"]
hyd = ["", "ひぇん"]
hye = ["", "ひぇ"]
hyh = ["", "ひゅう"]
hyj = ["", "ひゅん"]
hyl = ["", "ひょん"]
hyn = ["", "ひゃん"]
hyo = ["", "ひょ"]
hyp = ["", "ひょう"]
hyq = ["", "ひゃい"]
hyu = ["", "ひゅ"]
hyw = ["", "ひぇい"]
hyz = ["", "ひゃん"]
hz = ["", "はん"]

i = ["", "い"]

ja = ["", "じゃ"]
jd = ["", "じぇん"]
je = ["", "じぇ"]
jh = ["", "じゅう"]
# 実は独自
ji = ["", "じ"]
# 独自
jk = ["", "じん"]
jj = ["", "じゅん"]
jl = ["", "じょん"]
jn = ["", "じゃん"]
jo = ["", "じょ"]
jp = ["", "じょう"]
jq = ["", "じゃい"]
ju = ["", "じゅ"]
jw = ["", "じぇい"]
jz = ["", "じゃん"]

ka = ["", "か"]
kd = ["", "けん"]
ke = ["", "け"]
kga = ["", "きゃ"]
kgd = ["", "きぇん"]
kge = ["", "きぇ"]
kgh = ["", "きゅう"]
kgj = ["", "きゅん"]
kgl = ["", "きょん"]
kgn = ["", "きゃん"]
kgo = ["", "きょ"]
kgp = ["", "きょう"]
kgq = ["", "きゃい"]
kgu = ["", "きゅ"]
kgw = ["", "きぇい"]
kgz = ["", "きゃん"]
kh = ["", "くう"]
ki = ["", "き"]
kj = ["", "くん"]
kk = ["", "きん"]
kl = ["", "こん"]
km = ["", "かも"]
kn = ["", "かん"]
ko = ["", "こ"]
kp = ["", "こう"]
kq = ["", "かい"]
kr = ["", "から"]
kt = ["", "こと"]
ku = ["", "く"]
kw = ["", "けい"]
kya = ["", "きゃ"]
kyd = ["", "きぇん"]
kye = ["", "きぇ"]
kyh = ["", "きゅう"]
kyj = ["", "きゅん"]
kyl = ["", "きょん"]
kyn = ["", "きゃん"]
kyo = ["", "きょ"]
kyp = ["", "きょう"]
kyq = ["", "きゃい"]
kyu = ["", "きゅ"]
kyw = ["", "きぇい"]
kyz = ["", "きゃん"]
kz = ["", "かん"]

ma = ["", "ま"]
md = ["", "めん"]
me = ["", "め"]
mga = ["", "みゃ"]
mgd = ["", "みぇん"]
mge = ["", "みぇ"]
mgh = ["", "みゅう"]
mgj = ["", "みゅん"]
mgl = ["", "みょん"]
mgn = ["", "みゃん"]
mgo = ["", "みょ"]
mgp = ["", "みょう"]
mgq = ["", "みゃい"]
mgu = ["", "みゅ"]
mgw = ["", "みぇい"]
mgz = ["", "みゃん"]
mh = ["", "むう"]
mi = ["", "み"]
mj = ["", "むん"]
mk = ["", "みん"]
ml = ["", "もん"]
mn = ["", "もの"]
ms = ["", "ます"]
mo = ["", "も"]
mp = ["", "もう"]
mq = ["", "まい"]
mt = ["", "また"]
"m u" = ["", "む"]
mw = ["", "めい"]
mya = ["", "みゃ"]
myd = ["", "みぇん"]
mye = ["", "みぇ"]
myh = ["", "みゅう"]
myj = ["", "みゅん"]
myl = ["", "みょん"]
myn = ["", "みゃん"]
myo = ["", "みょ"]
myp = ["", "みょう"]
myq = ["", "みゃい"]
myu = ["", "みゅ"]
myw = ["", "みぇい"]
myz = ["", "みゃん"]
mz = ["", "まん"]

na = ["", "な"]
nb = ["", "ねば"]
nd = ["", "ねん"]
ne = ["", "ね"]
nga = ["", "にゃ"]
ngd = ["", "にぇん"]
nge = ["", "にぇ"]
ngh = ["", "にゅう"]
ngj = ["", "にゅん"]
ngl = ["", "にょん"]
ngn = ["", "にゃん"]
ngo = ["", "にょ"]
ngp = ["", "にょう"]
ngq = ["", "にゃい"]
ngu = ["", "にゅ"]
ngw = ["", "にぇい"]
ngz = ["", "にゃん"]
nh = ["", "ぬう"]
ni = ["", "に"]
nj = ["", "ぬん"]
nk = ["", "にん"]
"n l" = ["", "のん"]
nn = ["", "ん"]
no = ["", "の"]
np = ["", "のう"]
nq = ["", "ない"]
nr = ["", "なる"]
nt = ["", "にち"]
nu = ["", "ぬ"]
nw = ["", "ねい"]
nya = ["", "にゃ"]
nyd = ["", "にぇん"]
nye = ["", "にぇ"]
nyh = ["", "にゅう"]
nyj = ["", "にゅん"]
nyl = ["", "にょん"]
nyn = ["", "にゃん"]
nyo = ["", "にょ"]
nyp = ["", "にょう"]
nyq = ["", "にゃい"]
nyu = ["", "にゅ"]
nyw = ["", "にぇい"]
nyz = ["", "にゃん"]
nz = ["", "なん"]

o = ["", "お"]

pa = ["", "ぱ"]
pd = ["", "ぺん"]
pe = ["", "ぺ"]
pga = ["", "ぴゃ"]
pgd = ["", "ぴぇん"]
pge = ["", "ぴぇ"]
pgh = ["", "ぴゅう"]
pgj = ["", "ぴゅん"]
pgl = ["", "ぴょん"]
pgn = ["", "ぴゃん"]
pgo = ["", "ぴょ"]
pgp = ["", "ぴょう"]
pgq = ["", "ぴゃい"]
pgu = ["", "ぴゅ"]
pgw = ["", "ぴぇい"]
pgz = ["", "ぴゃん"]
ph = ["", "ぷう"]
pi = ["", "ぴ"]
pj = ["", "ぷん"]
pk = ["", "ぴん"]
pl = ["", "ぽん"]
pn = ["", "ぱん"]
po = ["", "ぽ"]
pp = ["", "ぽう"]
pq = ["", "ぱい"]
pu = ["", "ぷ"]
pw = ["", "ぺい"]
pya = ["", "ぴゃ"]
pyd = ["", "ぴぇん"]
pye = ["", "ぴぇ"]
pyh = ["", "ぴゅう"]
pyj = ["", "ぴゅん"]
pyl = ["", "ぴょん"]
pyn = ["", "ぴゃん"]
pyo = ["", "ぴょ"]
pyp = ["", "ぴょう"]
pyq = ["", "ぴゃい"]
pyu = ["", "ぴゅ"]
pyw = ["", "ぴぇい"]
pyz = ["", "ぴゃん"]
pz = ["", "ぱん"]

ra = ["", "ら"]
rd = ["", "れん"]
re = ["", "れ"]
rh = ["", "るう"]
ri = ["", "り"]
rj = ["", "るん"]
rk = ["", "りん"]
rl = ["", "ろん"]
rn = ["", "らん"]
ro = ["", "ろ"]
rp = ["", "ろう"]
rq = ["", "らい"]
rr = ["", "られ"]
ru = ["", "る"]
rw = ["", "れい"]
rya = ["", "りゃ"]
ryd = ["", "りぇん"]
rye = ["", "りぇ"]
ryh = ["", "りゅう"]
ryj = ["", "りゅん"]
ryl = ["", "りょん"]
ryn = ["", "りゃん"]
ryo = ["", "りょ"]
ryp = ["", "りょう"]
ryq = ["", "りゃい"]
ryu = ["", "りゅ"]
ryw = ["", "りぇい"]
ryz = ["", "りゃん"]
rz = ["", "らん"]

q = ["", "ん"]

sa = ["", "さ"]
sd = ["", "せん"]
se = ["", "せ"]
sh = ["", "すう"]
si = ["", "し"]
sj = ["", "すん"]
sk = ["", "しん"]
sl = ["", "そん"]
sn = ["", "さん"]
so = ["", "そ"]
sp = ["", "そう"]
sq = ["", "さい"]
sr = ["", "する"]
st = ["", "した"]
su = ["", "す"]
sw = ["", "せい"]
sya = ["", "しゃ"]
syd = ["", "しぇん"]
sye = ["", "しぇ"]
syh = ["", "しゅう"]
syj = ["", "しゅん"]
syl = ["", "しょん"]
syn = ["", "しゃん"]
syo = ["", "しょ"]
syp = ["", "しょう"]
syq = ["", "しゃい"]
syu = ["", "しゅ"]
syw = ["", "しぇい"]
syz = ["", "しゃん"]
sz = ["", "さん"]

ta = ["", "た"]
tb = ["", "たび"]
td = ["", "てん"]
te = ["", "て"]
# 独自
tgh = ["", "てゅう"]
tgi = ["", "てぃ"]
# 独自。tgiの派生
tgk = ["", "てぃん"]
tgu = ["", "とぅ"]
th = ["", "つう"]
ti = ["", "ち"]
tj = ["", "つん"]
tk = ["", "ちん"]
tl = ["", "とん"]
tm = ["", "ため"]
tn = ["", "たん"]
to = ["", "と"]
tp = ["", "とう"]
tq = ["", "たい"]
tr = ["", "たら"]
tt = ["", "たち"]
tu = ["", "つ"]
tw = ["", "てい"]
tya = ["", "ちゃ"]
tyd = ["", "ちぇん"]
tye = ["", "ちぇ"]
tyh = ["", "ちゅう"]
tyj = ["", "ちゅん"]
tyl = ["", "ちょん"]
tyn = ["", "ちゃん"]
tyo = ["", "ちょ"]
typ = ["", "ちょう"]
tyq = ["", "ちゃい"]
tyu = ["", "ちゅ"]
tyw = ["", "ちぇい"]
tyz = ["", "ちゃん"]
tz = ["", "たん"]

u = ["", "う"]

va = ["", "ゔぁ"]
ve = ["", "ゔぇ"]
vi = ["", "ゔぃ"]
vo = ["", "ゔぉ"]
vu = ["", "ゔ"]

wa = ["", "わ"]
wd = ["", "うぇん"]
we = ["", "うぇ"]
wi = ["", "うぃ"]
wk = ["", "うぃん"]
wl = ["", "うぉん"]
wn = ["", "わん"]
wo = ["", "を"]
wp = ["", "うぉー"]
wq = ["", "わい"]
wr = ["", "われ"]
# 独自
wse = ["", "ゑ"]
# 独自
wsi = ["", "ゐ"]
wso = ["", "うぉ"]
wt = ["", "わた"]
wu = ["", "う"]
wz = ["", "わん"]

xa = ["", "しゃ"]
xd = ["", "しぇん"]
xe = ["", "しぇ"]
xh = ["", "しゅう"]
# 独自
xi = ["", "し"]
xj = ["", "しゅん"]
# 独自
xk = ["", "しん"]
xl = ["", "しょん"]
xn = ["", "しゃん"]
xo = ["", "しょ"]
xp = ["", "しょう"]
xq = ["", "しゃい"]
# 独自。SKKとの競合回避
xtu = ["", "っ"]
xu = ["", "しゅ"]
xw = ["", "しぇい"]
# 独自。SKKとの競合回避
xxa = ["", "ぁ"]
# 独自。SKKとの競合回避
xxe = ["", "ぇ"]
# 独自
xxh = ["", "←"]
# 独自。SKKとの競合回避
xxi = ["", "ぃ"]
# 独自
xxj = ["", "↓"]
# 独自
xxk = ["", "↑"]
# 独自
xxl = ["", "→"]
# 独自。SKKとの競合回避
xxo = ["", "ぉ"]
# 独自。SKKとの競合回避
xxtu = ["", "っ"]
# 独自。SKKとの競合回避
xxu = ["", "ぅ"]
# 独自。SKKとの競合回避
xxya = ["", "ゃ"]
# 独自。SKKとの競合回避
xxyo = ["", "ょ"]
# 独自。SKKとの競合回避
xxyu = ["", "ゅ"]
# 独自。SKKとの競合回避
xya = ["", "ゃ"]
# 独自。SKKとの競合回避
xyo = ["", "ょ"]
# 独自。SKKとの競合回避
xyu = ["", "ゅ"]
# 独自
xwa = ["", "ゎ"]
xz = ["", "しゃん"]
# 独自。SKKとの競合回避
"x bracketleft" = ["", "「"]

ya = ["", "や"]
yh = ["", "ゆう"]
yj = ["", "ゆん"]
yl = ["", "よん"]
yn = ["", "やん"]
yo = ["", "よ"]
yp = ["", "よう"]
yq = ["", "やい"]
yr = ["", "よる"]
yu = ["", "ゆ"]
yz = ["", "やん"]

# 独自
z = ["", "　"]
# 独自
"z comma" = ["", "‥"]
# 独自
"z parenleft" = ["", "（"]
# 独自
"z parenright" = ["", "）"]
# 独自
"z minus" = ["", "〜"]
# 独自
"z period" = ["", "…"]
# 独自
"z slash" = ["", "・"]
# 独自
"z bracketleft" = ["", "『"]
# 独自
"z bracketright" = ["", "』"]
za = ["", "ざ"]
zc = ["", "ざ"]
zd = ["", "ぜん"]
ze = ["", "ぜ"]
zh = ["", "ずう"]
zi = ["", "じ"]
zj = ["", "ずん"]
zk = ["", "じん"]
zl = ["", "ぞん"]
zn = ["", "ざん"]
zo = ["", "ぞ"]
zp = ["", "ぞう"]
zq = ["", "ざい"]
zr = ["", "ざる"]
zu = ["", "ず"]
zv = ["", "ざい"]
zw = ["", "ぜい"]
zx = ["", "ぜい"]
zya = ["", "じゃ"]
zyd = ["", "じぇん"]
zye = ["", "じぇ"]
zyh = ["", "じゅう"]
zyj = ["", "じゅん"]
zyl = ["", "じょん"]
zyn = ["", "じゃん"]
zyo = ["", "じょ"]
zyp = ["", "じょう"]
zyq = ["", "じゃい"]
zyu = ["", "じゅ"]
zyw = ["", "じぇい"]
zyz = ["", "じゃん"]
zz = ["", "ざん"]
# 独自
"z braceleft" = ["", "【"]
# 独自
"z braceright" = ["", "】"]


[command]
[direct.hiragana]
"l" = [
    "ForceKanaConvert(Hiragana)",
    "ChangeInputMode(Ascii)",
    "FlushPreviousCarryOver",
]
"L" = [
    "ForceKanaConvert(Hiragana)",
    "ChangeInputMode(Zenkaku)",
    "FlushPreviousCarryOver",
]
"C-q" = [
    "ForceKanaConvert(Hiragana)",
    "ChangeInputMode(HankakuKatakana)",
    "FlushPreviousCarryOver",
]
"bracketleft" = [
    "ForceKanaConvert(Hiragana)",
    "ChangeInputMode(Katakana)",
    "FlushPreviousCarryOver",
]
"braceleft" = ["ChangeCompositionMode(PreComposition)"]
"C-j" = ["FinishKeyEvent"]
"C-g" = ["Abort"]
"C-G" = ["Abort"]
"Return" = ["ConfirmDirect"]
"C-m" = ["ConfirmDirect"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-H" = ["Delete"]
"slash" = ["ChangeCompositionMode(Abbreviation)"]

[direct.katakana]
"l" = [
    "ForceKanaConvert(Katakana)",
    "ChangeInputMode(Ascii)",
    "FlushPreviousCarryOver",
]
"L" = [
    "ForceKanaConvert(Katakana)",
    "ChangeInputMode(Zenkaku)",
    "FlushPreviousCarryOver",
]
"C-q" = [
    "ForceKanaConvert(Katakana)",
    "ChangeInputMode(HankakuKatakana)",
    "FlushPreviousCarryOver",
]
"bracketleft" = [
    "ForceKanaConvert(Katakana)",
    "ChangeInputMode(Hiragana)",
    "FlushPreviousCarryOver",
]
"braceleft" = ["ChangeCompositionMode(PreComposition)"]
"C-j" = ["FinishKeyEvent"]
"C-g" = ["Abort"]
"C-G" = ["Abort"]
"Return" = ["ConfirmDirect"]
"C-m" = ["ConfirmDirect"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-H" = ["Delete"]
"slash" = ["ChangeCompositionMode(Abbreviation)"]

[direct.hankakukatakana]
"l" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ChangeInputMode(Ascii)",
    "FlushPreviousCarryOver",
]
"L" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ChangeInputMode(Zenkaku)",
    "FlushPreviousCarryOver",
]
"C-q" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ChangeInputMode(Katakana)",
    "FlushPreviousCarryOver",
]
"bracketleft" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ChangeInputMode(Hiragana)",
    "FlushPreviousCarryOver",
]
"braceleft" = ["ChangeCompositionMode(PreComposition)"]
"C-j" = ["FinishKeyEvent"]
"C-g" = ["Abort"]
"C-G" = ["Abort"]
"Return" = ["ConfirmDirect"]
"C-m" = ["ConfirmDirect"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-H" = ["Delete"]
"slash" = ["ChangeCompositionMode(Abbreviation)"]

[direct.zenkaku]
"C-g" = ["Abort"]
"C-j" = ["ChangeInputMode(Hiragana)"]
"Return" = ["ConfirmDirect"]
"C-m" = ["ConfirmDirect"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-H" = ["Delete"]

[direct.ascii]
"C-g" = ["Abort"]
"C-j" = ["ChangeInputMode(Hiragana)"]
"Return" = ["ConfirmDirect"]
"C-m" = ["ConfirmDirect"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-H" = ["Delete"]


[pre_composition.hiragana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Katakana)",
    "ConfirmAs(Katakana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(HankakuKatakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]

[pre_composition.katakana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(HankakuKatakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(Katakana)",
    "ConfirmAs(Katakana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]

[pre_composition.hankakukatakana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(Katakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ConfirmAs(HankakuKatakana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]

[pre_compisition_okurigana.hiragana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Katakana)",
    "ConfirmAs(Katakana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(HankakuKatakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]

[pre_compisition_okurigana.katakana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(HankakuKatakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(Katakana)",
    "ConfirmAs(Katakana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]

[pre_compisition_okurigana.hankakukatakana]
"space" = ["TryNextCandidate"]
"bracketleft" = [
    "ForceKanaConvert(Hiragana)",
    "ConfirmAs(Hiragana)",
    "ChangeCompositionMode(Direct)",
]
"C-q" = ["ConfirmAs(Katakana)", "ChangeCompositionMode(Direct)"]
"C-g" = ["ClearUnconfirmedInputs", "Abort"]
"C-j" = [
    "ForceKanaConvert(HankakuKatakana)",
    "ConfirmAs(HankakuKatakana)",
    "ChangeCompositionMode(Direct)",
]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"Tab" = ["TryNextCompletion"]


[abbreviation.hiragana]
"space" = ["TryNextCandidate"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-j" = ["ConfirmAs(Ascii)", "ChangeCompositionMode(Direct)"]
"C-q" = ["ConfirmAs(Zenkaku)", "ChangeCompositionMode(Direct)"]
"Tab" = ["TryNextCompletion"]

[abbreviation.katakana]
"space" = ["TryNextCandidate"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-j" = ["ConfirmAs(Ascii)", "ChangeCompositionMode(Direct)"]
"C-q" = ["ConfirmAs(Zenkaku)", "ChangeCompositionMode(Direct)"]
"Tab" = ["TryNextCompletion"]

[abbreviation.hankakukatakana]
"space" = ["TryNextCandidate"]
"BackSpace" = ["Delete"]
"C-h" = ["Delete"]
"C-j" = ["ConfirmAs(Ascii)", "ChangeCompositionMode(Direct)"]
"C-q" = ["ConfirmAs(Zenkaku)", "ChangeCompositionMode(Direct)"]
"Tab" = ["TryNextCompletion"]


[composition_selection.hiragana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Escape" = ["Abort"]
"C-g" = ["Abort"]
"X" = ["Purge", "ChangeCompositionMode(Direct)"]
"space" = ["TryNextCandidate"]
"x" = ["TryPreviousCandidate"]
"BackSpace" = ["ConfirmComposition", "Delete"]
"C-h" = ["ConfirmComposition", "Delete"]
"bracketleft" = ["ConfirmComposition", "ChangeInputMode(Katakana)"]
"C-q" = ["ConfirmComposition", "ChangeInputMode(HankakuKatakana)"]

[composition_selection.katakana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Escape" = ["Abort"]
"C-g" = ["Abort"]
"X" = ["Purge", "ChangeCompositionMode(Direct)"]
"space" = ["TryNextCandidate"]
"BackSpace" = ["ConfirmComposition", "Delete"]
"C-h" = ["ConfirmComposition", "Delete"]
"bracketleft" = ["ConfirmComposition", "ChangeInputMode(Hiragana)"]
"C-q" = ["ConfirmComposition", "ChangeInputMode(HankakuKatakana)"]

[composition_selection.hankakukatakana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Escape" = ["Abort"]
"C-g" = ["Abort"]
"X" = ["Purge", "ChangeCompositionMode(Direct)"]
"space" = ["TryNextCandidate"]
"BackSpace" = ["ConfirmComposition", "Delete"]
"C-h" = ["ConfirmComposition", "Delete"]
"bracketleft" = ["ConfirmComposition", "ChangeInputMode(Hiragana)"]
"C-q" = ["ConfirmComposition", "ChangeInputMode(Katakana)"]


[completion.hiragana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Tab" = ["NextCandidatePointer"]
"period" = ["NextCandidatePointer"]
"(shift Tab)" = ["PreviousCandidatePointer"]
"comma" = ["PreviousCandidatePointer"]
"C-g" = ["Abort"]
"Escape" = ["Abort"]
"BackSpace" = ["ConfirmComposition", "Delete"]

[completion.katakana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Tab" = ["NextCandidatePointer"]
"period" = ["NextCandidatePointer"]
"(shift Tab)" = ["PreviousCandidatePointer"]
"comma" = ["PreviousCandidatePointer"]
"C-g" = ["Abort"]
"Escape" = ["Abort"]
"BackSpace" = ["ConfirmComposition", "Delete"]

[completion.hankakukatakana]
"Return" = ["ConfirmComposition"]
"C-j" = ["ConfirmComposition"]
"Tab" = ["NextCandidatePointer"]
"period" = ["NextCandidatePointer"]
"(shift Tab)" = ["PreviousCandidatePointer"]
"comma" = ["PreviousCandidatePointer"]
"C-g" = ["Abort"]
"Escape" = ["Abort"]
"BackSpace" = ["ConfirmComposition", "Delete"]
