tap "ebc-2in2crc/zlibcmd"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "koekeishiya/formulae"
tap "rhysd/hgrep", "https://github.com/rhysd/hgrep"
tap "universal-ctags/universal-ctags"
tap "xecua/repo", "git@github.com:xecua/homebrew-repo"
brew "openjdk"
brew "antlr"
brew "python@3.9"
brew "glib"
brew "bat"
brew "bat-extras"
brew "binutils"
brew "pkg-config"
brew "libxcb"
brew "libx11"
brew "bottom"
brew "cmake"
brew "coreutils"
brew "cpanminus"
brew "curl"
brew "delve"
brew "deno"
brew "direnv"
brew "dmd"
brew "docutils"
brew "elixir"
brew "dos2unix"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "firebase-cli"
brew "fish"
brew "fzf"
brew "zstd"
brew "gcc"
brew "gh"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-filter-repo"
brew "git-lfs"
brew "git-now"
brew "glow"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "go"
brew "gopls"
brew "gpatch"
brew "gradle"
brew "groff"
brew "haskell-stack"
brew "hexyl"
brew "htop"
brew "insect"
brew "iproute2mac"
brew "jid"
brew "jq"
brew "kotlin"
brew "latex2rtf"
brew "libgpg-error"
brew "llvm"
brew "mas"
brew "mercurial"
brew "neofetch"
brew "neovim"
brew "ninja"
brew "nkf"
brew "nmap"
brew "openjdk@11"
brew "openjdk@8"
brew "openssh"
brew "pandoc"
brew "pastel"
brew "pdfpc"
brew "peco"
brew "perl"
brew "ripgrep"
brew "ruby"
brew "rename"
brew "rust-analyzer"
brew "sccache"
brew "starship"
brew "staticcheck"
brew "texlab"
brew "thefuck"
brew "tig"
brew "trash-cli"
brew "unar"
brew "watch"
brew "wget"
brew "with-readline"
brew "yapf"
brew "yarn"
brew "ebc-2in2crc/zlibcmd/zlibcmd"
brew "koekeishiya/formulae/skhd", args: ["with-logging"]
brew "koekeishiya/formulae/yabai"
brew "rhysd/hgrep/hgrep"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "android-studio"
cask "aquaskk"
cask "cakebrew"
cask "clipy"
cask "cloudflare-warp"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "f5vpn"
cask "figma"
cask "firefox-developer-edition"
cask "flutter"
cask "font-3270"
cask "font-cica"
cask "font-cinecaption"
cask "font-freefont"
cask "font-haranoaji"
cask "font-inter"
cask "font-ipaexfont"
cask "font-kin-iro-sans-serif"
cask "font-koharuiro-sunray"
cask "font-komorebi-gothic"
cask "font-last-resort"
cask "font-mplus"
cask "font-myrica"
cask "font-myricam"
cask "font-noto-sans-cjk-jp"
cask "font-noto-serif-cjk-jp"
cask "font-rolachan"
cask "font-source-han-code-jp"
cask "font-source-han-sans"
cask "google-drive"
cask "gpg-suite"
cask "hetimazip-qlgenerator"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "mactex-no-gui"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "qbittorrent"
cask "qlmarkdown"
cask "obs"
cask "qlstephen"
cask "scroll-reverser"
cask "skim"
cask "spotify"
cask "termhere"
cask "thunderbird"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "xquartz"
cask "zotero"
mas "BetterTDeck for TweetDeck", id: 1549421502
mas "Bitwarden", id: 1352778147
mas "GhostText", id: 1552641506
mas "GoodNotes", id: 1444383602
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Slack", id: 803453959
mas "Todoist", id: 585829637
mas "Twitter", id: 1482454543
mas "Userscripts", id: 1463298887
mas "Vimari", id: 1480933944
mas "WakeOnCommand", id: 1484204619
