[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_ft = ['snippet']
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Robzz/deoplete-omnisharp'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source  = ['denite.nvim']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['cpp']
hook_add = """
let g:deoplete#sources#clang#libclang_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang'
"""
on_source = ['deoplete.nvim']


[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp']
hook_add = """
function! CPPCodeCleanup()
  let l:lines='all'
  let g:clang_format_fallback_style = 'Google'
  :pyf /usr/local/share/clang/clang-format.py
endfunction
command! CPPCodeCleanup call CPPCodeCleanup()
autocmd BufWrite *.{cpp} :CPPCodeCleanup
"""

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = ['python']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = "othree/es.next.syntax.vim"
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'Valloric/YouCompleteMe'
on_ft = ['javascript']

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs']
build = 'xbuild server/OmniSharp.sln'

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown','mkd']

# twitter
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/TweetVim'

# TeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']


[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']
