# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${env_var.ZMX_SESSION}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""
add_newline = true

[directory]
fish_style_pwd_dir_length = 1

[env_var.ZMX_SESSION]
symbol = " "
format = "[$symbol$env_value]($style) "
description = "zmx session name"
style = "bold magenta"

[character]
success_symbol = '''[INSERT❯](bold green)'''
error_symbol = '''[INSERT❯](bold red)'''
vimcmd_symbol = "[NORMAL❯](bold blue)"
vimcmd_replace_one_symbol = "[REPLACE❯](bold purple)"
vimcmd_replace_symbol = "[REPLACE❯](bold purple)"
vimcmd_visual_symbol = "[VISUAL❯](bold yellow)"

[status]
disabled = false
format = '[$symbol]($style)'
symbol = '''\(ﾉ∀`\)'''
success_symbol = '''\(´∀`\)'''
style = 'bold'

[git_branch]
symbol = " " # U+E702, Devicons

[git_commit]
tag_disabled = false
tag_max_candidates = 1

[line_break]
disabled = true

[nix_shell]
symbol = ' ' # U+E843, Devicons
