---
packages:
  s-tui: app-admin/s-tui
  sudo: app-admin/sudo
  unar: app-arch/unar

  # - app-admin/s-tui
  # - app-admin/sudo
  # - app-arch/unar
  # - app-containers/docker
  # - app-containers/docker-cli
  # - app-containers/docker-compose
  # - app-crypt/gnupg
  # - app-crypt/libu2f-host
  # - app-crypt/yubikey-manager-qt
  # - app-crypt/yubioath-desktop
  # - app-editors/neovim
  # - app-editors/vscode
  # - app-i18n/fcitx:5
  # - app-i18n/fcitx-configtool:5
  # - app-i18n/fcitx-gtk:5
  # - app-i18n/fcitx-qt:5
  # - app-i18n/fcitx-skk:5
  # - app-i18n/libskk
  # - app-misc/neofetch
  # - app-misc/tmux
  # - app-misc/jq
  # - app-misc/trash-cli
  # - app-misc/ranger
  # - app-portage/eix
  # - app-portage/flaggie
  # - app-portage/gentoolkit
  # - app-portage/smart-live-rebuild
  # - app-shells/fish
  # - app-shells/fzf
  # - app-shells/starship
  # - app-shells/thefuck
  # - app-text/diffpdf
  # - app-text/zathura
  # - app-text/zathura-pdf-mupdf
  # - dev-lang/go
  # - dev-lang/rust
  # - dev-java/gradle-bin
  # - dev-java/openjdk-bin
  # - dev-java/openjdk-bin:11
  # - dev-java/openjdk-bin:17
  # - dev-perl/rename
  # - dev-python/neovim-remote
  # - dev-python/pip
  # - dev-python/pynvim
  # - dev-python/pkginfo
  # - dev-python/xkeysnail
  # - dev-python/yapf
  # - dev-util/cargo-ebuild
  # - dev-util/ccache
  # - dev-util/ctags
  # - dev-util/radare2
  # - dev-util/git-delta
  # - dev-util/pkgcheck
  # - dev-util/pkgdev
  # - dev-util/sccache
  # - dev-vcs/gibo
  # - dev-vcs/git-filter-repo
  # - dev-vcs/tig
  # - mail-client/thunderbird-bin
  # - mail-mta/proton-mail-bridge
  # - media-fonts/harano-aji-fonts
  # - media-fonts/inter
  # - media-fonts/ipaex
  # - media-fonts/fontawesome
  # - media-fonts/corefonts
  # - media-fonts/noto
  # - media-fonts/noto-emoji
  # - media-fonts/udev-gothic
  # - media-gfx/feh
  # - media-gfx/graphviz
  # - media-gfx/imagemagick
  # - media-libs/fontconfig
  # - media-libs/portaudio
  # - media-sound/alsa-util
  # - media-sound/bluez-alsa
  # - media-sound/pavucontrol-qt
  # - media-tv/v4l-utils
  # - media-video/ffmpeg
  # - media-video/pipewire
  # - media-video/simplescreenrecorder
  # - media-video/obs-studio
  # - media-video/v4l2loopback
  # - net-analyzer/nmap
  # - net-analyzer/traceroute
  # - net-analyzer/wireshark
  # - net-fs/cifs-utils
  # - net-im/discord-bin
  # - net-im/slack
  # - net-libs/nodejs
  # - net-misc/grive
  # - net-wireless/blueman
  # - net-wireless/bluez
  # - sys-apps/bat
  # - sys-apps/bat-extras
  # - sys-apps/dbus
  # - sys-apps/exa
  # - sys-apps/fd
  # - sys-apps/pv
  # - sys-apps/ripgrep
  # - sys-apps/yarn
  # - sys-block/gparted
  # - sys-block/parted
  # - sys-devel/clang
  # - sys-devel/gdb
  # - sys-devel/distcc
  # - sys-fs/fuse
  # - sys-fs/fuse-exfat
  # - sys-fs/inotify-tools
  # - sys-fs/ntfs3g
  # - sys-fs/udiskie
  # - sys-fs/udisks
  # - sys-kernel/dracut
  # - sys-kernel/linux-firmware
  # - sys-libs/efivar
  # - sys-process/bottom
  # - sys-process/htop
  # - sys-process/nvtop
  # - www-client/vivaldi
  # - www-servers/caddy
  # - x11-apps/setxkbmap
  # - x11-apps/xwininfo
  # - x11-base/xorg-server
  # - x11-drivers/nvidia-drivers
  # - x11-misc/clipcat
  # - x11-misc/dex
  # - x11-misc/dunst
  # - x11-misc/lightdm
  # - x11-misc/lightdm-slick-greeter
  # - x11-misc/picom
  # - x11-misc/rofi
  # - x11-misc/shutter
  # - x11-misc/spacefm
  # - x11-misc/xdg-utils
  # - x11-misc/xss-lock
