# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# IDE support
## LSP Client
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0

## if there is no stable LSP Server
[[plugins]]
repo = 'dense-analysis/ale'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# explorer
[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = "kristijanhusak/defx-git"

[[plugins]]
repo = "kristijanhusak/defx-icons"

[[plugins]]
repo = 'mbbill/undotree'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# Neosnippet
[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Template
[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'subnut/nvim-ghost.nvim'

# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# Syntax Highlighting
## markdown
[[plugins]]
repo = 'tpope/vim-markdown'

## fish
[[plugins]]
repo = 'dag/vim-fish'

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## Swift
[[plugins]]
repo = 'apple/swift'
rtp = 'utils/vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

## TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'

## React
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

## Java
[[plugins]]
repo = 'vim-jp/vim-java'

## json
[[plugins]]
repo = 'kevinoid/vim-jsonc'

## F#
[[plugins]]
repo = 'ionide/Ionide-vim'

## Brewfile
[[plugins]]
repo = 'bfontaine/Brewfile.vim'
