# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Utility
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# startup
[[plugins]]
repo = 'mhinz/vim-startify'

# Preview
[[plugins]]
repo = 'previm/previm'
depends = ['open-browser.vim'] # optional

# open URL
[[plugins]]
repo = 'tyru/open-browser.vim'

# Window resize mode
[[plugins]]
repo = 'sedm0784/vim-resize-mode'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# diagnostics
[[plugins]]
repo = 'folke/trouble.nvim'
depends = ['nvim-web-devicons'] # optional

## dependency
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Grammar check
[[plugins]]
repo = 'rhysd/vim-grammarous'

# Ghosttext
[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'

## Installer
[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim']

[[plugins]]
repo = 'mfussenegger/nvim-jdtls'

## DAP
[[plugins]]
repo = 'mfussenegger/nvim-dap'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
depends = ['nvim-dap']

## tsserver integration
[[plugins]]
repo = 'jose-elias-alvarez/typescript.nvim'

## Formatter with LSP interface
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'MunifTanjim/prettier.nvim'
depends = ['nvim-lspconfig', 'null-ls.nvim']

# Popup
[[plugins]]
repo = 'Shougo/pum.vim'

# denops
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = ['denops.vim']

## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-around'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-file'
depends = ['denops.vim', 'ddc.vim']

## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['denops.vim', 'ddu.vim']

### UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
depends = ['denops.vim', 'ddu.vim']

### Matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
depends = ['denops.vim', 'ddu.vim']

### Sources
[[plugins]]
repo = 'Shougo/ddu-source-action'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = '4513ECHO/ddu-source-source'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'shun/ddu-source-buffer'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'shun/ddu-source-rg'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-register'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
depends = ['denops.vim', 'ddu.vim']

### Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-kind-word'
depends = ['denops.vim', 'ddu.vim']

### column
[[plugins]]
repo = 'Shougo/ddu-column-filename'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
depends = ['denops.vim', 'ddu.vim']

# filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
rev = 'main'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['nerdfont.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# other
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

# editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# parenthesis control
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']

## dependency
[[plugins]]
repo = 'kana/vim-operator-user'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# undo
[[plugins]]
repo = 'mbbill/undotree'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons'] # optional

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'alvan/vim-closetag'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
# repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Template
[[plugins]]
repo = 'thinca/vim-template'

# cursor
[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'skanehira/jumpcursor.vim'

# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# Syntax Highlighting
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

## fish
[[plugins]]
repo = 'dag/vim-fish'

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

## F#
[[plugins]]
repo = 'ionide/Ionide-vim'

## Brewfile
[[plugins]]
repo = 'bfontaine/Brewfile.vim'

## ebuild and etc
[[plugins]]
repo = 'gentoo/gentoo-syntax'

## CoPL Derivation Language
[[plugins]]
repo = 'ymyzk/vim-copl'

## CSV (Rainbow and SQL-like query)
[[plugins]]
repo = 'mechatroner/rainbow_csv'

## Firestore Security Rule
[[plugins]]
repo = 'delphinus/vim-firestore'

# Rust tooltip
[[plugins]]
repo = 'simrat39/rust-tools.nvim'
