# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# terminal
[[plugins]]
repo = 'Shougo/deol.nvim'

## open new tabpage instead of start nested instance
[[plugins]]
repo = 'lambdalisue/guise.vim'

# Utility
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# startup
[[plugins]]
repo = 'mhinz/vim-startify'

# Preview
[[plugins]]
repo = 'previm/previm'
depends = ['open-browser.vim'] # optional

# open URL
[[plugins]]
repo = 'tyru/open-browser.vim'

# nonsense animation
[[plugins]]
repo = 'eandrju/cellular-automaton.nvim'

[[plugins]]
repo = 'epwalsh/obsidian.nvim'
depends = ['plenary.nvim']

# Window resize mode
[[plugins]]
repo = 'sedm0784/vim-resize-mode'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# quickfix
[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'

# diagnostics
[[plugins]]
repo = 'folke/trouble.nvim'
depends = ['nvim-web-devicons'] # optional

[[plugins]]
repo = 'folke/todo-comments.nvim'

# popup notification
[[plugins]]
repo = 'rcarriga/nvim-notify'

## dependency
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Grammar check
[[plugins]]
repo = 'rhysd/vim-grammarous'

# Ghosttext
[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'

# Machine Learning-based completion
[[plugins]]
repo = 'github/copilot.vim'

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'

## Installer
[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['nvim-lspconfig', 'mason.nvim']

[[plugins]]
repo = 'tamago324/nlsp-settings.nvim'

[[plugins]]
repo = 'mfussenegger/nvim-jdtls'

## DAP
[[plugins]]
repo = 'mfussenegger/nvim-dap'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
depends = ['nvim-dap']

## outliner
[[plugins]]
repo = 'simrat39/symbols-outline.nvim'

[[plugins]]
repo = 'SmiteshP/nvim-navic'
depends = ['nvim-lspconfig']

## tsserver integration
[[plugins]]
repo = 'jose-elias-alvarez/typescript.nvim'

## efm-langserver presets
[[plugins]]
repo = 'creativenull/efmls-configs-nvim'

## Rust tooltip
[[plugins]]
repo = 'simrat39/rust-tools.nvim'

## Flutter integration
[[plugins]]
repo = 'akinsho/flutter-tools.nvim'

# Popup
[[plugins]]
repo = 'Shougo/pum.vim'

# denops
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = ['denops.vim']

## SKK
[[plugins]]
# repo = 'vim-skk/skkeleton'
repo = 'xecua/skkeleton'
depends = ['denops.vim']

[[plugins]]
repo = 'skk-dev/dict'

[[plugins]]
repo = 'uasi/skk-emoji-jisyo'

## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']

### ui
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['denops.vim', 'ddc.vim', 'pum.vim']

### source
[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-copilot'
depends = ['denops.vim', 'ddc.vim', 'copilot.vim']

[[plugins]]
repo = 'LumaKernel/ddc-tabnine' # 動くかなあ

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'ttak0422/ddc-source-nvim-obsidian'

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'

### filter
[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
depends = ['denops.vim', 'ddc.vim']

## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['denops.vim', 'ddu.vim']

### UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
depends = ['denops.vim', 'ddu.vim']

### Matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'

### Sources
[[plugins]]
repo = 'Shougo/ddu-source-action'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-help'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-man'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = '4513ECHO/ddu-source-source'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'nabezokodaikon/ddu-source-file_fd'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'shun/ddu-source-buffer'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'shun/ddu-source-rg'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-register'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'kyoh86/ddu-source-command'

### Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-kind-word'
depends = ['denops.vim', 'ddu.vim']

### column
[[plugins]]
repo = 'Shougo/ddu-column-filename'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
depends = ['denops.vim', 'ddu.vim']

# filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
rev = 'main'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['nerdfont.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

# parenthesis control
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']

## dependency
[[plugins]]
repo = 'kana/vim-operator-user'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# undo
[[plugins]]
repo = 'mbbill/undotree'

# statusline
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'arkav/lualine-lsp-progress'
depends = ['lualine.nvim']

# comment
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# Open README.md
[[plugins]]
repo = '4513ECHO/vim-readme-viewer'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'alvan/vim-closetag'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# snippets
[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

# Template
[[plugins]]
repo = 'thinca/vim-template'

# cursor
[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'skanehira/jumpcursor.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'monaqa/dial.nvim'

# Highlight under cursor
[[plugins]]
repo = 'RRethy/vim-illuminate'

# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'preservim/vim-indent-guides'

# Syntax Highlighting
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'nvim-treesitter/playground'

[[plugins]]
repo = 'HiPhish/nvim-ts-rainbow2'

## fish
[[plugins]]
repo = 'dag/vim-fish'

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

## F#
[[plugins]]
repo = 'ionide/Ionide-vim'

## Brewfile
[[plugins]]
repo = 'bfontaine/Brewfile.vim'

## ebuild etc
[[plugins]]
repo = 'gentoo/gentoo-syntax'

## CoPL Derivation Language
[[plugins]]
repo = 'ymyzk/vim-copl'

## CSV (Rainbow and SQL-like query)
[[plugins]]
repo = 'mechatroner/rainbow_csv'

## Firestore Security Rule
[[plugins]]
repo = 'delphinus/vim-firestore'

## skk-jisyo
[[plugins]]
repo = 'vim-skk/skkdict.vim'

## astro.build
[[plugins]]
repo = 'wuelnerdotexe/vim-astro'
