# Preview
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'rst', 'asciidoc'] # あとtextileもあるらしい

# Syntax Highlighting
## dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

## Haxe
[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = ['haxe']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]]
repo = 'rhysd/vim-grammarous'
on_ft = ['tex', 'satysfi', 'markdown', 'rst', 'asciidoc']

[[plugins]]
repo = 'vim-skk/skkeleton'
if = 'exists("g:neovide")'
