# Preview
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'rst', 'asciidoc'] # あとtextileもあるらしい

# Go auto import
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

#
[[plugins]]
repo = 'rhysd/vim-grammarous'
on_ft = ['tex', 'satysfi', 'markdown', 'rst', 'asciidoc']

# Syntax Highlighting
## Haxe
[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = ['haxe']

## Swift
[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']
