# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Utility
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# startup
[[plugins]]
repo = 'mhinz/vim-startify'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'mfussenegger/nvim-jdtls'

[[plugins]]
repo = 'jose-elias-alvarez/nvim-lsp-ts-utils'

## Formatter (via LSP)
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'

[[plugins]]
repo = 'MunifTanjim/prettier.nvim'

## if there is no stable LSP Server
[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'github/copilot.vim'

# denops/ddc.vim
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'matsui54/ddc-nvim-lsp-doc'

# explorer
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# parenthesis control
[[plugins]]
repo = 'tpope/vim-surround'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'mbbill/undotree'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'alvan/vim-closetag'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
# repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Template
[[plugins]]
repo = 'thinca/vim-template'

# Fuzzy Finder
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'junegunn/fzf.vim'

# [[plugins]]
# repo = 'subnut/nvim-ghost.nvim'

[[plugins]]
repo = 'rhysd/accelerated-jk'

# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# Syntax Highlighting
## Python (following latest syntax)
[[plugins]]
repo = 'vim-python/python-syntax'

## markdown
[[plugins]]
repo = 'tpope/vim-markdown'

## fish
[[plugins]]
repo = 'dag/vim-fish'

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

## TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'

## React
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

## Java
[[plugins]]
repo = 'uiiaoo/java-syntax.vim'

## json
[[plugins]]
repo = 'kevinoid/vim-jsonc'

## F#
[[plugins]]
repo = 'ionide/Ionide-vim'

## Brewfile
[[plugins]]
repo = 'bfontaine/Brewfile.vim'

## ebuild and etc
[[plugins]]
repo = 'gentoo/gentoo-syntax'

## toml
[[plugins]]
repo = "cespare/vim-toml"

## GraphQL
[[plugins]]
repo = 'jparise/vim-graphql'

## Prisma
[[plugins]]
repo = 'pantharshit00/vim-prisma'

## CoPL Derivation Language
[[plugins]]
repo = 'ymyzk/vim-copl'

## Kotlin
[[plugins]]
repo = 'udalov/kotlin-vim'
