# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Utility
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# startup
[[plugins]]
repo = 'mhinz/vim-startify'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# diagnostics
[[plugins]]
repo = 'folke/trouble.nvim'

## dependency
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'mfussenegger/nvim-jdtls'

[[plugins]]
repo = 'jose-elias-alvarez/nvim-lsp-ts-utils'

## Formatter with LSP interface
[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'

[[plugins]]
repo = 'MunifTanjim/prettier.nvim'

# Popup
[[plugins]]
repo = 'Shougo/pum.vim'

# denops
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'

[[plugins]]
repo = 'matsui54/denops-signature_help'

## ddc
[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'LumaKernel/ddc-file'

## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'

### UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'

### Matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

### Sources
[[plugins]]
repo = '4513ECHO/ddu-source-source'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'

### Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

# explorer
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

# editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# parenthesis control
[[plugins]]
repo = 'tpope/vim-surround'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'mbbill/undotree'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'alvan/vim-closetag'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
# repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Template
[[plugins]]
repo = 'thinca/vim-template'

# Fuzzy Finder
[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'junegunn/fzf.vim'

# [[plugins]]
# repo = 'subnut/nvim-ghost.nvim'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'skanehira/jumpcursor.vim'

# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# Syntax Highlighting
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

## markdown
[[plugins]]
repo = 'tpope/vim-markdown'

## fish
[[plugins]]
repo = 'dag/vim-fish'

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

## F#
[[plugins]]
repo = 'ionide/Ionide-vim'

## Brewfile
[[plugins]]
repo = 'bfontaine/Brewfile.vim'

## ebuild and etc
[[plugins]]
repo = 'gentoo/gentoo-syntax'

## CoPL Derivation Language
[[plugins]]
repo = 'ymyzk/vim-copl'

## CSV (Rainbow and SQL-like query)
[[plugins]]
repo = 'mechatroner/rainbow_csv'

## Firestore Security Rule
[[plugins]]
repo = 'delphinus/vim-firestore'

# Rust tooltip
[[plugins]]
repo = 'simrat39/rust-tools.nvim'
on_ft = ['rust']
