[theme]
theme = "solarized-dark"
[theme.overrides]
separator = " \ue0b2"

[icons]
icons = "awesome"

[[block]]
block = "xrandr"

[[block]]
block = "cpu"
format = "$icon  $barchart $utilization @ $frequency"

[[block]]
block = "load"
format = "$icon  $1m.eng(4) / $5m.eng(4) / $15m.eng(4)"

[[block]]
block = "nvidia_gpu"

[[block]]
block = "memory"

[[block]]
block = "net"
format = "$icon  $ip ^icon_net_up $speed_up.eng(3,B,K) ^icon_net_down $speed_down.eng(3,B,K)"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
format = "$icon $combo.rot-str(20,60) $play $next"
hide_when_empty = true

[[block]]
block = "custom"
command = "echo `whoami` @ `cat /etc/hostname`"
interval = "once"

[[block]]
block = "battery"
format = " $icon  $percentage "

[[block]]
block = "time"
format = " $icon %Y/%m/%d(%a) %H:%M:%S"
