theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "xrandr"

[[block]]
block = "cpu"
format = "{barchart} {utilization} @ {frequency}"

[[block]]
block = "load"
format = "{1m:4} / {5m:4} / {15m:4}"

[[block]]
block = "nvidia_gpu"

[[block]]
block = "memory"
format_mem = "{mem_used;G} /{mem_total;G} ({mem_used_percents:1})"
clickable = false

[[block]]
block = "net"
format = "{ip} {speed_up;K} {speed_down;K}"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
marquee_interval = 60
hide_when_empty = true

[[block]]
block = "custom"
command = "echo `whoami` @ `cat /etc/hostname`"
interval = "once"

[[block]]
block = "time"
format = "%Y/%m/%d(%a) %H:%M:%S"
