[theme]
theme = "solarized-dark"
[theme.overrides]
separator = " \ue0b2"
end_separator = " "

[icons]
icons = "awesome"

[[block]]
block = "xrandr"

[[block]]
block = "cpu"
format = "$icon  $barchart $utilization @ $frequency"

[[block]]
block = "load"
format = "$icon  $1m.eng(4) / $5m.eng(4) / $15m.eng(4)"

[[block]]
block = "nvidia_gpu"
format = "$icon $name $utilization $memory $temperature"
error_format = ""
error_interval = 0

[[block]]
block = "memory"
format = "$icon $mem_used.eng(3,B,M)/$mem_total.eng(3,B,M) ($mem_used_percents.eng(2))"
format_alt = "$icon_swap $swap_used.eng(3,B,M)/$swap_total.eng(3,B,M) ($swap_used_percents.eng(2))"

[[block]]
block = "net"
format = "$icon  $ip ^icon_net_up $speed_up.eng(3,B,K) ^icon_net_down $speed_down.eng(3,B,K)"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
format = "{$icon $combo.rot-str(20,60)| $play $next|}"

[[block]]
block = "custom"
command = "echo `whoami` @ `cat /etc/hostname`"
interval = "once"

[[block]]
block = "battery"
format = "$icon  $percentage"
missing_format = ""

[[block]]
block = "time"
format = "$icon %Y/%m/%d(%a) %H:%M:%S"
