[theme]
theme = "solarized-dark"
[theme.overrides]
separator = " \ue0b2"
end_separator = " "

[icons]
icons = "material-nf"

[[block]]
block = "xrandr"

[[block]]
block = "cpu"
format = "$icon  $barchart $utilization @ $frequency"

[[block]]
block = "load"
format = "$icon  $1m.eng(w:4) / $5m.eng(w:4) / $15m.eng(w:4)"

[[block]]
block = "amd_gpu"
format = "$icon $vram_used_percents $vram_total"
error_format = ""
error_interval = 0
[[block]]
block = "nvidia_gpu"
format = "$icon $name $utilization $memory $temperature"
error_format = ""
error_interval = 0

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:3,u:B,p:M)/$mem_total.eng(w:3,u:B,p:M) ($mem_used_percents.eng(w:2))"
format_alt = "$icon_swap $swap_used.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M) ($swap_used_percents.eng(w:2))"

[[block]]
block = "net"
format = "$icon  $ip ^icon_net_up $speed_up.eng(w:3,u:B,p:M) ^icon_net_down $speed_down.eng(w:3,u:B,p:M)"

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "music"
player = "spotify"
format = "{$icon $combo.str(w:30,rot_interval:30) $play  $next|}"

# [[block]]
# block = "custom"
# command = "echo `whoami` @ `cat /etc/hostname`"
# interval = "once"

[[block]]
block = "battery"
format = "$icon  $percentage"
missing_format = ""

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%Y/%m/%d(%a) %H:%M:%S')"
interval = 10
