## ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hooks_file = '$STD_CONFIG/dpp/ddu.lua'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_cmd = 'Ddu'
group = 'ddu'

### UI
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
group = 'ddu'
[plugins.ftplugin]
lua_ddu-ff = """
local opts = { buffer = true, silent = true }
vim.keymap.set("n", "<CR>", "<Cmd>call ddu#ui#do_action('itemAction')<CR>", opts)
-- function()
--     local item = vim.fn["ddu#ui#get_item"]()
--     if item["__sourceName"] == "rg" then
--       -- wincmd pだとpreviewに行ってしまうのでダメ
--     end
--     vim.fn["ddu#ui#do_action"]("itemAction")
-- end, opts)
vim.keymap.set("n", "a", "<Cmd>call ddu#ui#do_action('chooseAction')<CR>", opts)
vim.keymap.set("n", "/", "<Cmd>call ddu#ui#do_action('openFilterWindow')<CR>", opts)
vim.keymap.set("n", ",", "<Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>", opts)
vim.keymap.set("n", "t", "<Cmd>call ddu#ui#do_action('toggleAllItems')<CR>", opts)
vim.keymap.set("n", "f", "<Cmd>call ddu#ui#do_action('itemAction', #{ name: 'quickfix' })<CR>", opts)
vim.keymap.set("n", "p", "<Cmd>call ddu#ui#do_action('togglePreview')<CR>", opts)
vim.keymap.set("n", "h", "<Cmd>call ddu#ui#do_action('collapseItem')<CR>", opts)
vim.keymap.set("n", "l", "<Cmd>call ddu#ui#do_action('expandItem')<CR>", opts)
vim.keymap.set("n", "q", "<Cmd>call ddu#ui#do_action('quit')<CR>", opts)

"""

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
group = 'ddu'
[[plugins.ftplugin]]
lua_ddu-filer = """
-- TODO: 開いたときに現在のファイルにカーソルが移動するやつ(頑張るしかない)とウィンドウ選んで(適当なプラグインを使おう)ファイルを開けるやつ
vim.opt_local.number = true
local opts = { buffer = true, silent = true }
vim.keymap.set("n", "a", "<Cmd>call ddu#ui#do_action('chooseAction')<CR>", opts)
vim.keymap.set("n", "h", "<Cmd>call ddu#ui#do_action('collapseItem')<CR>", opts)
vim.keymap.set("n", "d", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'trash' })<CR>", opts)
vim.keymap.set("n", "N", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'newFile' })<CR>", opts)
vim.keymap.set("n", "K", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'newDirectory' })<CR>", opts)
vim.keymap.set("n", "R", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'rename' })<CR>", opts)
vim.keymap.set("n", "y", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'yank' })<CR>", opts)
vim.keymap.set("n", "p", "<Cmd>call ddu#ui#do_action('itemAction', #{name: 'paste' })<CR>", opts)

vim.keymap.set("n", "s", function()
    if not vim.fn["ddu#ui#get_item"]()["isTree"] then
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "wincmd p|wincmd s|drop" } })
    end
end, opts)
vim.keymap.set("n", "v", function()
    if not vim.fn["ddu#ui#get_item"]()["isTree"] then
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "wincmd p|wincmd v|drop" } })
    end
end, opts)
vim.keymap.set("n", "t", function()
    if not vim.fn["ddu#ui#get_item"]()["isTree"] then
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "tab drop" } })
    end
end, opts)
vim.keymap.set("n", "e", function()
    if not vim.fn["ddu#ui#get_item"]()["isTree"] then
        local picked_window_id = require("window-picker").pick_window()
        local picked_window_nr = vim.api.nvim_win_get_number(picked_window_id)
        vim.fn["ddu#ui#do_action"](
            "itemAction",
            { name = "open", params = { command = picked_window_nr .. "wincmd w|drop" } }
        )
    end
end, opts)
vim.keymap.set("n", "l", function()
    if vim.fn["ddu#ui#get_item"]()["isTree"] then
        vim.fn["ddu#ui#do_action"]("expandItem", { isInTree = true })
        -- isInTreeがtrueなら↓も呼んでくれてはいるんだけど効かん……
        vim.fn["ddu#ui#do_action"]("cursorNext")
    else
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "wincmd p|drop" } })
    end
end, opts)
vim.keymap.set("n", "<LeftRelease>", function()
    local item = vim.fn["ddu#ui#get_item"]()
    if item["isTree"] and item["__expanded"] then
        vim.fn["ddu#ui#do_action"]("collapseItem")
    elseif item["isTree"] then
        vim.fn["ddu#ui#do_action"]("expandItem", { isInTree = true })
    else
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "wincmd p|drop" } })
    end
end, opts)

vim.keymap.set("n", "<CR>", function()
    if vim.fn["ddu#ui#get_item"]()["isTree"] then
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "narrow" })
    else
        vim.fn["ddu#ui#do_action"]("itemAction", { name = "open", params = { command = "wincmd p|drop" } })
    end
end, opts)

vim.keymap.set(
    "n",
    "<BS>",
    "<Cmd>call ddu#ui#do_action('itemAction', #{ name: 'narrow', params: #{ path: '..' } })<CR>",
    opts
)

vim.keymap.set("n", "!", function()
    -- これdocに記載されてるやり方だから↑のヒントになりそう
    local current = vim.fn["ddu#custom#get_current"](vim.b.ddu_ui_name)
    local matchers = ((current["sourceOptions"] or {})["file"] or {})["matchers"] or {}
    if #matchers == 0 then
        matchers = { "matcher_hidden" }
    else
        matchers = {}
    end

    vim.print(current["sourceOptions"])

    vim.fn["ddu#ui#do_action"]("updateOptions", {
        sourceOptions = { file = { matchers = matchers } },
    })
    vim.fn["ddu#ui#do_action"]("redraw", { method = "refreshItems" })
end, opts)
"""

### Matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
group = 'ddu'

[[plugins]]
repo = 'mityu/ddu-filter-matcher_multi_regex'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
group = 'ddu'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
group = 'ddu'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'
group = 'ddu'

### Sources
[[plugins]]
repo = 'Shougo/ddu-source-action'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-help'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-man'
group = 'ddu'

[[plugins]]
repo = '4513ECHO/ddu-source-source'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-source-file'
group = 'ddu'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
group = 'ddu'

[[plugins]]
repo = 'shun/ddu-source-buffer'
group = 'ddu'

[[plugins]]
repo = 'shun/ddu-source-rg'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-source-register'
group = 'ddu'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
group = 'ddu'

### Kinds
[[plugins]]
repo = 'Shougo/ddu-kind-file'
group = 'ddu'

[[plugins]]
repo = 'Shougo/ddu-kind-word'
group = 'ddu'

### column
[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
group = 'ddu'
