# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json#/$defs/tasks

- name: Sync and update world
  ansible.builtin.import_tasks: update.yml
- name: Emerge eselect-repository in advance
  ansible.builtin.import_tasks: emerge.yml
  vars:
    packages:
      - eselect-repository
- name: Add repositories
  ansible.builtin.import_tasks: eselect_repository.yml
- name: Emerge packages
  ansible.builtin.import_tasks: emerge.yml
  # TODO: 適切なUSEフラグを定義するのを先にやるべき
  when: false
  vars:
    packages: "{{ emerge_packages }}"
