[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_post_source = 'call DeopleteHookPostSource()'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_ft = ['snippet']
depends = ['deoplete.nvim','neosnippet-snippets']
on_event = 'InsertEnter'
hook_post_source = 'call NeosnippetHookPostSource()'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
depends = ['deoplete.nvim']
on_event = 'InsertEnter'
build = './install.sh'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']
on_source = ['deoplete.nvim']
hook_source = 'call DeopleteClangHookSource()'

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'lambdalisue/vim-backslash'
on_ft = ['vim']

# Syntax Highlighting
## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'
on_ft = ['gitignore']

## Swift
[[plugins]]
repo = 'apple/swift'
rtp = 'utils/vim'
on_ft = ['swift']

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'
on_ft = ['satysfi']

## TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'typescript']

## React
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascriptreact', 'typescriptreact']

