[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'kana/vim-smartinput'

# autocomplete plugin(replaced with smartinput)
[[plugins]]
repo = 'cohama/lexima.vim'
# on_i = 1 : deprecated. We should use below
on_event = 'InsertEnter'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim','ale']

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# helpの日本語化
repo = 'vim-jp/vimdoc-ja'
