# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# task runner
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# IDE support
## LSP Client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

## if there is no stable LSP Server
[[plugins]]
repo = 'dense-analysis/ale'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# autocomplete matching brace/quotation
[[plugins]]
repo = 'cohama/lexima.vim'

# for good appearance
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# explorer
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']

[[plugins]]
repo ="kristijanhusak/defx-git"

[[plugins]]
repo ="kristijanhusak/defx-icons"

[[plugins]]
repo = 'mbbill/undotree'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# show underscore for matching parenthesis
[[plugins]]
repo = 'itchyny/vim-parenmatch'

# comment out tool
[[plugins]]
repo = 'preservim/nerdcommenter'

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# Syntax Highlighting
## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'

## Swift
[[plugins]]
repo = 'apple/swift'
rtp = 'utils/vim'

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'

# Neosnippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Haxe
[[plugins]]
repo = 'jdonaldson/vaxe'

