[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# LSP Client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = '0'
# rev = 'release'

# linter
# [[plugins]]
# repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-fugitive'

# Automatically complete closing brace
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# [[plugins]]
# repo = 'maximbaz/lightline-ale'
# depends = ['lightline.vim','ale']

# [[plugins]]
# repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo =  'itchyny/lightline.vim'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# helpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# ペースト時にpasteモードに
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
