# indentation
[[plugins]]
repo = 'lambdalisue/vim-backslash'
on_ft = ['vim']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

# Preview
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown', 'rst', 'asciidoc'] # あとtextileもあるらしい

# Syntax Highlighting
## markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown','mkd']

## fish
[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

## toml
[[plugins]]
repo = "cespare/vim-toml"
on_ft = ['toml']

## .gitignore file
[[plugins]]
repo = 'benknoble/gitignore-vim'
on_ft = ['gitignore']

## Swift
[[plugins]]
repo = 'apple/swift'
rtp = 'utils/vim'
on_ft = ['swift']

## SATySFi
[[plugins]]
repo = 'qnighy/satysfi.vim'
on_ft = ['satysfi']

## TypeScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'typescript']

## React
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['javascriptreact', 'typescriptreact']

# Haxe
[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = ['haxe']

# Java
[[plugins]]
repo = 'vim-jp/vim-java'
on_ft = ['java']
