#!/usr/bin/env bash
if [[ -e /var/cache/eix/portage.eix ]]; then
    rsync -ca /var/cache/eix/portage.eix /var/cache/eix/previous.eix;
fi

eix-update
eix-remote update

if [[ -e /var/cache/eix/previous.eix ]]; then
    eix-diff;
fi
