height = 16
font = "monospace 10"
command = "i3status-rs"

background = "383838ff"
color = "#000000ff"
tag_focused_fg = "#1d2021ff"
tag_focused_bg = "#287828ff"
tag_fg = "#1d2021ff"
tag_bg = "#287828ff"
tags_padding = 10
tags_r = 5
