modmap:
  - name: default
    remap:
      capslock: ctrl_l
      # SandS
      space:
        held: shift_l
        alone: space
        free_hold: true
      henkan:
        held: shift_l
        alone: space
        free_hold: true
      muhenkan:
        held: shift_r
        alone: space
        free_hold: true
