import { TSSnippet } from "https://deno.land/x/denippet_vim@v0.6.0/loader.ts";

const r = String.raw;

export const snippets: Record<string, TSSnippet> = {
  base: {
    body: [
      r`\documentclass{jlreq}`,
      r`% \documentclass[a4j,uplatex]{jsarticle} % upLaTeX`,
      r`% \documentclass[a4j]{ltjsarticle} % LuaTeX`,
      r`% \documentclass[notheorems,dvipdfmx]{beamer} % upLaTeX`,
      r`% \documentclass[notheorems]{beamer} % LuaTeX`,
      "",
      "%%% beamer %%%",
      r`% \usepackage[notheorems]{beamerarticle} % Handout`,
      "",
      "% theme",
      r`% \usetheme{Madrid}`,
      r`% \usetheme{metropolis}`,
      "",
      "%% theme: focus",
      r`% \usepackage[colorgrid,gridunit=pt,texcoord]{eso-pic} % position check (for absolute positioning)`,
      "",
      r`% \usetheme[numbering=none,nofirafonts]{focus}`,
      r`% \definecolor{alert}{RGB}{242,114,0}`,
      r`% \definecolor{accent}{RGB}{0,118,186}`,
      r`% \setbeamercolor{titlelike}{bg=accent}`,
      r`% \setbeamertemplate{footline}[none]`,
      r`%% disable \scshape(small caps)`,
      r`% \setbeamerfont*{title}{size=\huge,shape=\bfseries}`,
      r`% \setbeamerfont*{subtitle}{size=\Large,parent=structure}`,
      r`% \setbeamerfont*{author}{size=\large}`,
      r`% \setbeamerfont*{date}{size=\large}`,
      r`% \setbeamerfont*{frametitle}{size=\Large}`,
      r`% \setbeamertemplate{frametitle}[default][center] % タイトルが中央揃えに`,
      r`% \AtBeginSection[]{`,
      r`%     % \begin{frame}{toc}`,
      r`%     %     \tableofcontents[sectionstyle=show/shaded,subsectionstyle=hide/hide/hide]`,
      r`%     % \end{frame}`,
      "% }",
      r`% \AtBeginSubsection[]{}`,
      r`% \renewcommand\baselinestretch{1.5}`,
      "",
      "%%% non-beamer %%%",
      r`% \renewcommand{\thesection}{\arabic{section}.}`,
      r`% \renewcommand{\thesubsection}{\arabic{section}.\arabic{subsection}.}`,
      r`% \renewcommand{\labelenumi}{\arabic{enumi}. }`,
      r`% \renewcommand{\labelenumii}{\arabic{enumi}.\arabic{enumii}. }`,
      r`% \usepackage[style=ieee,citetracker=true]{biblatex}`,
      "",
      "%%% common %%%",
      r`\usepackage{mypreamble}`,
      r`\usepackage[enable]{easy-todo}`,
      r`% \addbibresource{reference.bib}`,
      r`\date{\today}`,
      r`\author{aaa}`,
      r`\title{aaa}`,
      r`% \subtitle{sub}`,
      "",
      "% Speaker note. Recommend to use with compatible presentation tool e.g. pympress",
      "% This command seems to have to come after loading mypreamble",
      r`% \setbeameroption{show notes on second screen=right}`,
      "",
      r`\pagestyle{no_running_head}`,
      "",
      r`\begin{document}`,
      r`%\begin{frame}`,
      r`\maketitle`,
      r`%\end{frame}`,
      r`\listoftodos`,
      "",
      r`%\printbibliography[title=参考文献]`,
      r`\end{document}`,
    ],
  },
  textpos: {
    body: [
      r`\begin{textblock*}{0.4\linewidth}(230pt, 100pt)`,
      r`  \centering`,
      "  \\includegraphics[width=\\linewidth]{${1:./figure.png}}",
      r`\end{textblock*}`,
    ],
  },
  indent: {
    body: [r`\begin{indentation}{1em}{0em}`, "  $0", r`\end{indentation}`],
  },
};
