#!/usr/bin/perl

if ($^O eq 'darwin') {
    $pdf_previewer = '/Applications/Skim.app/Contents/MacOS/Skim';
} elsif ($^O eq 'linux') {
    $pdf_previewer = 'zathura';
}

$latex = 'uplatex -kanji=utf-8 -halt-on-error -interaction=nonstopmode -file-line-error -synctex=1';
$latex_silent = 'uplatex -kanji=utf-8 -halt-on-error -interaction=batchmode -file-line-error -synctex=1';
$lualatex = 'lualatex -interaction=nonstopmode -synctex=1S';
$dvipdf = 'dvipdfmx -o %D %S';
$bibtex = 'upbibtex';
$makeindex = 'mendex';

$pdf_mode = 3;
$max_repeat = 5;
$out_dir = 'out';

$pvc_view_file_via_temporary = 0;

