#!/usr/bin/perl

my $fd_replace = 'fd . -t f ".tex$" -0 | xargs -0 sed -i "" -e "s/、/，/g" -e "s/。/．/g";';
my $find_replace = 'find . -type f -name "*.tex" -print0 | xargs -0 sed -i "" -e "s/、/，/g" -e "s/。/．/g";';

if ($^O eq 'darwin') {
    if (!system('fd -V >/dev/null')) {
        $replace = $fd_replace
    } else {
        $replace = $find_replace
    }

    $latex = $replace . '/Library/TeX/texbin/uplatex -kanji=utf-8 -halt-on-error -interaction=nonstopmode -file-line-error -synctex=1';
    $latex_silent = $replace . '/Library/TeX/texbin/uplatex -kanji=utf-8 -halt-on-error -interaction=batchmode -file-line-error -synctex=1';
    $lualatex = $replace . '/Library/TeX/texbin/lualatex -interaction=nonstopmode -synctex=1S';
    $dvipdf = '/Library/TeX/texbin/dvipdfmx -o %D %S';
    $bibtex = '/Library/TeX/texbin/pbibtex';
    $makeindex = '/Library/TeX/texbin/mendex';
    $pdf_previewer = '/Applications/Skim.app/Contents/MacOS/Skim';
} elsif ($^O eq 'linux') {
    if (!system('fd -V >/dev/null')) {
        $replace = $fd_replace
    } else {
        $replace = $find_replace
    }

    $latex = $replace . '/usr/bin/uplatex -kanji=utf-8 -halt-on-error -interaction=nonstopmode -file-line-error -synctex=1';
    $latex_silent = $replace . '/usr/bin/uplatex -kanji=utf-8 -halt-on-error -interaction=batchmode -file-line-error -synctex=1';
    $lualatex = $replace . '/usr/bin/lualatex -interaction=nonstopmode -synctex=1S';
    $dvipdf = '/usr/bin/dvipdfmx -o %D %S';
    $bibtex = '/usr/bin/pbibtex';
    $makeindex = '/usr/bin/mendex';
    $pdf_previewer = '/usr/bin/zathura';
}
# TODO: add configuration for other OSs

$pdf_mode = 3;
$max_repeat = 5;
$out_dir = 'out';

$pvc_view_file_via_temporary = 0;
